FROM node:20-alpine AS build

WORKDIR /app/frontend

COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci

COPY frontend ./

RUN npm run build

FROM node:20-alpine

ENV NODE_ENV=production

WORKDIR /app/frontend

COPY --from=build /app/frontend ./

EXPOSE 3000

CMD ["npm", "run", "start"]
